version: '2'

services:
  mongo:
    image: mongo:4.0
    ports:
      - 27017:27017
    # logging:
    #   driver: none
  api:
    build: ./services/api
    volumes:
      - $PWD/services/api:/app:Z
    environment:
      - PORT=3000
      - MONGO_URL=mongodb://mongo:27017/games
      - ENDPOINT=/api
      - DEBUG=api:info:*
    ports:
      - 3000:3000
    depends_on:
      - mongo
    tty: true